name: API Tests CI/CD

on:
  workflow_dispatch:
    inputs:
      testTask:
        description: 'Test task to run (smoke or bots)'
        required: true
        default: 'smoke'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      EMAIL_GET_TOKEN: ${{ secrets.EMAIL_GET_TOKEN }}
      PASSWORD_GET_TOKEN: ${{ secrets.PASSWORD_GET_TOKEN }}
      API_KEY_EXCHANGE: ${{ secrets.API_KEY_EXCHANGE }}
      SECRET_EXCHANGE: ${{ secrets.SECRET_EXCHANGE }}

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: ❎ ⌛ Check Java version
        run: java -version
      - name: ❎ ⌛ Check JVM version
        run: echo $JAVA_HOME
      - name: ❎ ⌛ Check Java Core version
        run: javac -version

      # 3. Make gradlew executable
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      - name: ❎ ⌛ Check Gradle version
        run: ./gradlew --version
      - name: ✅ 🚿 Clean Gradle build
        run: ./gradlew clean
      - name: ✅ ⚙️ Install Allure
        run: npm install -g allure-commandline
      - name: ❎ ⌛ Check Allure version
        run: allure --version
      # 4. Run Tests
      - name: Run Tests
        run: |
          ./gradlew clean ${{ github.event.inputs.testTask }} \
          -Pemail=$EMAIL_GET_TOKEN \
          -Ppassword=$PASSWORD_GET_TOKEN \
          -PapiKeyExchange=$API_KEY_EXCHANGE \
          -PsecretExchange=$SECRET_EXCHANGE

      # 5. Generate Allure Report
      - name: Generate Allure Report
        run: ./gradlew allureReport
      - name: ✅ 💾 Load previous test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: ✅ 🤖 Build allure report on gh-pages
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      - name: ✅ 💻 Publish test report
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
