name: API Tests CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Позволяет вручную запускать workflow
    inputs:
      testTask:
        description: 'Test task to run (smoke or bots)'
        required: true
        default: 'smoke'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      EMAIL_GET_TOKEN: ${{ secrets.EMAIL_GET_TOKEN }}
      PASSWORD_GET_TOKEN: ${{ secrets.PASSWORD_GET_TOKEN }}
      API_KEY_EXCHANGE: ${{ secrets.API_KEY_EXCHANGE }}
      SECRET_EXCHANGE: ${{ secrets.SECRET_EXCHANGE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run Tests
        run: |
          ./gradlew clean ${{ github.event.inputs.testTask }} \
          -Pemail=$EMAIL_GET_TOKEN \
          -Ppassword=$PASSWORD_GET_TOKEN \
          -PapiKeyExchange=$API_KEY_EXCHANGE \
          -PsecretExchange=$SECRET_EXCHANGE

      - name: Collect test results
        run: |
          # Создаем папку для результатов тестов, если она не существует
          mkdir -p test-results
          
          # Перемещаем результаты тестов из Gradle в папку test-results
          mv build/test-results/test/ test-results/

      - name: Archive test results as ZIP
        run: |
          # Создаем архив из папки test-results
          zip -r test-results.zip test-results/

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.zip
